const PRODUCT_LIST_REQUESTED = 'PRODUCT_LIST_REQUESTED'
const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED'

const PRODUCT_DETAILS_REQUESTED = 'PRODUCT_DETAILS_REQUESTED'
const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED'

export {
    PRODUCT_LIST_REQUESTED,
    PRODUCT_LIST_SUCCESS,
    PRODUCT_LIST_FAILED,
    PRODUCT_DETAILS_FAILED,
    PRODUCT_DETAILS_REQUESTED,
    PRODUCT_DETAILS_SUCCESS
}