const PRODUCT_LIST_REQUESTED = 'PRODUCT_LIST_REQUESTED'
const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED'

export { PRODUCT_LIST_REQUESTED, PRODUCT_LIST_SUCCESS, PRODUCT_LIST_FAILED }